// <auto-generated />
using System;
using Jose_Ortega_P2_Ap1.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jose_Ortega_P2_Ap1.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Shared.Models.Accesorios", b =>
                {
                    b.Property<int>("AccesorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccesorioId");

                    b.ToTable("Accesorios");

                    b.HasData(
                        new
                        {
                            AccesorioId = 1,
                            Descripcion = "Camara trasera"
                        },
                        new
                        {
                            AccesorioId = 2,
                            Descripcion = "Pantalla interior"
                        },
                        new
                        {
                            AccesorioId = 3,
                            Descripcion = "Interior en piel"
                        },
                        new
                        {
                            AccesorioId = 4,
                            Descripcion = "Sun Roof"
                        },
                        new
                        {
                            AccesorioId = 5,
                            Descripcion = "Aros de lujo"
                        });
                });

            modelBuilder.Entity("Shared.Models.Vehiculos", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gastos")
                        .HasColumnType("TEXT");

                    b.HasKey("VehiculoId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Shared.Models.VehiculosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccesorioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Accesorios")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Vehiculos")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("Accesorios");

                    b.HasIndex("Vehiculos");

                    b.ToTable("VehiculosDetalle");
                });

            modelBuilder.Entity("Shared.Models.VehiculosDetalle", b =>
                {
                    b.HasOne("Shared.Models.Accesorios", null)
                        .WithMany("VehiculosDetalle")
                        .HasForeignKey("Accesorios");

                    b.HasOne("Shared.Models.Vehiculos", null)
                        .WithMany("VehiculosDetalle")
                        .HasForeignKey("Vehiculos");
                });

            modelBuilder.Entity("Shared.Models.Accesorios", b =>
                {
                    b.Navigation("VehiculosDetalle");
                });

            modelBuilder.Entity("Shared.Models.Vehiculos", b =>
                {
                    b.Navigation("VehiculosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
